version: "3.9"

services:
  server:
    build:
      context: ./server
    environment:
      - HOME_DIRECTORY=/parse
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client
      args:
        HOME_DIRECTORY: /parse
    depends_on:
      - server
    ports:
      - "8084:80"
    environment:
      - HOME_DIRECTORY=/parse
