version: "3.9"

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"

  client:
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "5173:80"

